[package]
name = "merkle_tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = "0.10.8"
hex-literal = "0.4.1"
num-bigint = "0.4.4"
num-traits = "0.2.17"
anyhow = "1.0.75"
